export default {
    EVENT_SCREEN_VIEWED: "Screen_Viewed",
    EVENT_NORMAL_SIGN_UP: "Signup",
    EVENT_SOCIAL_SIGNUP: "Signup",
    EVENT_LOGOUT: "Logout",
    EVENT_NORMAL_LOGIN: "Login",
    EVENT_SOCIAL_LOGIN: "Login",
    EVENT_LOCATION: "Location",
    EVENT_SEARCH: "Search",
    EVENT_CATEGORY_VIEW: "Category_View",
    EVENT_PRODUCT_VIEW: "Product_View",
    EVENT_ADD_TO_WISHLIST: "Add_To_Wishlists",
    EVENT_REMOVE_FROM_WISHLIST: "Remove_From_Wishlist",
    EVENT_ADD_TO_CART: "Add_To_Cart",
    EVENT_REMOVE_FROM_CART: "Delete_From_Cart",
    EVENT_COUPON_APPLIED: "Coupon",
    EVENT_ADD_ADDRESS: "Add_New_Address",
    EVENT_STORE_LOCATOR: "Store_Locator",
    EVENT_CHECKOUT: "Checkout",
    PAYMENT_METHOD: "Payment_Method",
    EVENT_PURCHASE: "Purchase",
    EVENT_PROFILE_UPDATE: "Profile_Update",
    EVENT_SETTINGS_UPDATE: "Settings_Update",
    EVENT_UPDATE_TIER: "Update_Tier",
    EVENT_PRODUCT_REVIEW: "Product_Review",
    EVENT_SHOPPING_FEEDBACK: "Shopping_Feedback",
    EVENT_VIEW_CART: "View_Cart",
    EVENT_SELECT_ADDRESS: "Select_Address",
    EVENT_SELECT_DELIVERY_TYPE: "Select_Delivery_Type",
    EVENT_COMPLETE_CHECKOUT: "Complete_Checkout",


    PARAMS_SCREEN_NAME: "ScreenName",
    PARAMS_USER_ID: "UserId",
    PARAMS_CREATED_AT: "CreatedAt",
    PARAM_CT_GENERATED: "CTGeneraed",
    PARAMS_USER_STATUS: "UserStatus",
    PARAMS_USER_NAME: "UserName",
    PARAMS_PHONE: "PhoneNo",
    PARAMS_DOB: "DOB",
    PARAMS_REG_TYPE: "RegistrationType",
    PARAMS_REQ_PLATFORM: "RegistrationPlatform",
    PARAMS_GENDER: "Gender",
    PARAMS_WALLET_ID: "WalletId",
    PARAMS_EMAIL_ID: "EmailID",
    PARAMS_TIER_TYPE: "TierType",
    PARAMS_DEVICE_DETAILS: "DeviceDetails",
    PARAMS_ZENDESK_ID: "ZendeskId",
    PARAMS_SOCIAL_ID: "socialId",
    PARAMS_LOCATION: "Location",
    PARAMS_CATEGORY_NAME: "CategoryName",
    PARAMS_CATEGORY_ID: "CategoryID",
    PARAMS_PRODUCT_ID: "ProductId",
    PARAMS_PRODUCT_NAME: "ProductName",
    PARAMS_FROM_SCREEN: "FromScreen",
    PARAMS_PRODUCT_SKU: "ProductSKU",
    PARAMS_PRICE: "Price",
    PARAMS_NAME: "Name",
    PARAMS_ADDRESS: "Address",
    PARAMS_CITY: "City",
    PARAMS_STATE: "State",
    PARAMS_PRODUCT_CAT_ID: "ProductCategoryID",
    PARAMS_DISCOUNT: "Discount",
    PARAMS_COUPON_CODE: "CouponCode",
    PARAMS_COUPON_TYPE: "CouponType",
    PARAMS_DISCOUNT_VALUE: "DiscountValue",
    PARAMS_COUPON_VALIDITY: "CouponValidity",
    PARAMS_ADDRESS_TYPE: "AddressType",
    PARAMS_COORDINATES: "Coordinates",
    PARAMS_PINCODE: "Pincode",
    PARAMS_LATTITUDE: "Latitude",
    PARAMS_LONGITTUDE: "Longitude",
    PARAMS_DELIVERY_TYPE: "DeliveryType",
    PARAMS_CART_ID: "CartID",
    PARAMS_QUANTITY: "Quantity",
    PARAMS_SUB_TOTAL: "SubTotal",
    PARAMS_COUPON_DISC: "CouponDiscount",
    PARAMS_SHIPPING_FEE: "ShippingFee",
    PARAMS_DONATION: "Donation",
    PARAMS_GRAND_TOTAL: "GrandTotal",
    PARAMS_CART_TYPE: "CartType",
    PARAMS_PAYMENT_METHOD: "PaymentMethod",
    PARAMS_ORDER_ID: "OrderID",
    PARAMS_ORDER_STATUS: "OrderStatus",
    PARAMS_OVERALL_RATING: "OverAllrating",
    PARAMS_RATING_TITLE: "RatingTitle",
    PARAMS_PERFORMANCE_RATING: "PerformanceRating",
    PARAMS_VALUE_RATING: "ValueRating",
    PARAMS_QUALITY_RATING: "QualityRating",
    PARAMS_NICK_NAME: "NickName",
    PARAMS_RATING_COMMENT: "RatingComment",
    PARAMS_RATING: "Rating",
    
    
    SCREEN_HOME: "Home",
    SCREEN_PLP: "PLP",
    SCREEN_SUB_CATEGORY_PLP: "Sub Category PLP Page",
    SCREEN_PLP_SEARCH: "PLPSearch",
    // SCREEN_SEARCH: "Search",
    SCREEN_SIGN_UP: "Signup",
    SCREEN_GIFT_HOME: "Gift Card Home",
    SCREEN_WISHLIST: "Wishlist",
    SCREEN_MY_ORDERS: "My Orders",
    SCREEN_FAQ: "FAQ",
    SCREEN_HELP_SUPPORT: "Help Support",
    // SCREEN_SETTINGS: "Settings",
    SCREEN_MY_BAG: "My Bag",
    // SCREEN_RECOMMEND: "Recommendation",
    // SCREEN_SHADE_SIZE: "Size Shade Screen",
    SCREEN_OFFERS: "Offers",
    // SCREEN_FREE_SAMPLE: "Free Sample",
    // SCREEN_CHECKOUT: "Checkout",
    SCREEN_ADDRESS: "Address",
    SCREEN_DELIVERY: "Delivery",
    SCREEN_PAYMENT: "Payment",
    SCREEN_PDP: "Product Detail",
    
    SCREEN_ACCOUNT: "My Account",
    SCREEN_DASHBOARD: "My Dashboard",
    SCREEN_MY_WALLET: "My Wallet",
    SCREEN_MY_PAYMENT_METHOD: "My Payment Method",
    SCREEN_MY_OFFER: "My Offer",
    SCREEN_SKIN_PREFERENCE: "Skin Preference",
    SCREEN_THANK_YOU: "Thank You",
    SCREEN_STORE_LOCATOR: "Store Locator Page",
    SCREEN_COUPON: "Coupon Page",
    SCREEN_MEMBERSHIP: "Membership Page",
    
}

