import { Typography } from "@material-ui/core";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>The BodyShop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Typography>Body shop</Typography>
    </>
  );
}
